### PR TITLE
Feature/maybe_more_concurrent_safely

### PR DESCRIPTION
**Pull request by drstranges**

### CODE REVIEW

**Comment by forresthopkinsa** [comment]
I think you might appreciate the [downstream](https://github.com/forresthopkinsa/StompProtocolAndroid)

**Comment by NaikSoftware** [comment]
@forresthopkinsa your branch have more clear code, and more rx.

**Comment by drstranges** [comment]
@forresthopkinsa, @NaikSoftware  yep, more clean, but I'd suggest some small changes.

**Comment by NaikSoftware** [comment]
Changes used in https://github.com/NaikSoftware/StompProtocolAndroid/pull/98

**Pull request closed without merging**
